stages:
  data_ingestion:
    cmd: python src/Transformers/pipelines/stage_01_data_ingestion.py
    deps:
      - src/Transformers/pipelines/stage_01_data_ingestion.py
      - src/Transformers/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data/